export const navData = [
  {
    url: "https://rukminim1.flixcart.com/flap/128/128/image/29327f40e9c4d26b.png?q=100",
    text: "Grocery",
    listItem: [
      {
        name: "Furniture Top Offers",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Bed Room Furniture",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Furnishing",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Smart Home Automation",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Improvement",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Decor",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Lighting",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Festive Decor & Gift",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
    ],
  },
  {
    url: "https://rukminim1.flixcart.com/flap/128/128/image/22fddf3c7da4c4f4.png?q=100",
    text: "Mobile",
    listItem: [
      {
        name: "Furniture Top Offers",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Bed Room Furniture",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Furnishing",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Smart Home Automation",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Improvement",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Decor",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Lighting",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Festive Decor & Gift",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
    ],
  },

  {
    url: "https://rukminim1.flixcart.com/flap/128/128/image/82b3ca5fb2301045.png?q=100",
    text: "Fashion",
    listItem: [
      {
        name: "Men's Top Wear",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Men's Botton Wear",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Men's Footwear",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Women Ethic",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Women Western",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Women Footwear",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Watch and Accessories",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Bags , Suitcases and Luggage",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
    ],
  },

  {
    url: "https://rukminim1.flixcart.com/flap/128/128/image/69c6589653afdb9a.png?q=100",
    text: "Electronics",
    listItem: [
      {
        name: "Furniture Top Offers",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Bed Room Furniture",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Furnishing",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Smart Home Automation",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Improvement",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Decor",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Lighting",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Festive Decor & Gift",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
    ],
  },
  {
    url: "https://rukminim1.flixcart.com/flap/128/128/image/ee162bad964c46ae.png?q=100",
    text: "Home",
    listItem: [
      {
        name: "Furniture Top Offers",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Bed Room Furniture",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Furnishing",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Smart Home Automation",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Improvement",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Decor",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Lighting",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Festive Decor & Gift",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
    ],
  },
  {
    url: "https://rukminim1.flixcart.com/flap/128/128/image/0ff199d1bd27eb98.png?q=100",
    text: "Appliances",
    listItem: [
      {
        name: "Television",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "New Launches",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Smart And Ultra HD",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Shop By Screen Size",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Washing Machine",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Air Conditioners",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Shop By Brand",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Refrigerators",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Kitchen Appliances",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Healthy Living",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
    ],
  },
  {
    url: "https://rukminim1.flixcart.com/flap/128/128/image/71050627a56b4693.png?q=100",
    text: "Travel",
    listItem: [
      {
        name: "Furniture Top Offers",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Bed Room Furniture",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Furnishing",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Smart Home Automation",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Improvement",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Decor",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Lighting",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Festive Decor & Gift",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
    ],
  },
  {
    url: "https://rukminim1.flixcart.com/flap/128/128/image/f15c02bfeb02d15d.png?q=100",
    text: "Top_Offers",
    listItem: [
      {
        name: "Furniture Top Offers",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Bed Room Furniture",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Furnishing",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Smart Home Automation",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Improvement",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Decor",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Lighting",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Festive Decor & Gift",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
    ],
  },
  {
    url: "https://rukminim1.flixcart.com/flap/128/128/image/dff3f7adcf3a90c6.png?q=100",
    text: "Beauty, Toys & More",
    listItem: [
      {
        name: "Furniture Top Offers",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Bed Room Furniture",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Furnishing",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Smart Home Automation",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Improvement",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Decor",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Home Lighting",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Festive Decor & Gift",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
    ],
  },

  {
    url: "https://rukminim1.flixcart.com/fk-p-flap/128/128/image/05d708653beff580.png?q=100",
    text: "Two_Wheelers",
    listItem: [
      {
        name: "Television",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "New Launches",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Smart And Ultra HD",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Shop By Screen Size",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Washing Machine",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Air Conditioners",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Shop By Brand",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Refrigerators",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Kitchen Appliances",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
      {
        name: "Healthy Living",
        subList: [
          { name: "Bed Room Furniture" },
          { name: "Furnishing" },
          { name: "Smart Home Automation" },
          { name: "Home Improvement" },
          { name: "Home Decor" },
          { name: "Home Lighting" },
          { name: "Festive Decor & Gift" },
        ],
      },
    ],
  },
];
